// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzhawtofvjtagpejtuik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6aGF3dG9mdmp0YWdwZWp0dWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NTI2OTAsImV4cCI6MjA2NTQyODY5MH0.SBwSVuJtDyKep7fG2RpAxSl4dJpe3vcJsxtFpqWimGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);